  
version: "3"

services:
  devapp:
    build: .
    container_name: sommelier-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/
    command:
      "python manage.py runserver 0.0.0.0:8000"
