# Generated by Django 3.0 on 2020-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
    ]
